apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: rxpulse-dev
  labels:
    app: inventory-service
    app.kubernetes.io/part-of: rxpulse
    app.kubernetes.io/managed-by: kubectl
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
