{{- $ns := .Values.namespace }}
{{- if .Values.global }}{{- if .Values.global.namespace }}{{- $ns = .Values.global.namespace }}{{- end }}{{- end }}
{{- $sec := .Values.secret }}
{{- if hasKey .Values "sealed-secrets" }}{{- if hasKey (index .Values "sealed-secrets") "secret" }}{{- $sec = index (index .Values "sealed-secrets") "secret" }}{{- end }}{{- end }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ $sec.name }}
  namespace: {{ $ns }}
spec:
  encryptedData:
    JWT_EXPIRES_IN: {{ $sec.encryptedJwtExpiresIn }}
    JWT_SECRET: {{ $sec.encryptedJwtSecret }}
    MONGO_CATALOG_URI: {{ $sec.encryptedMongoCatalogUri }}
    MONGO_INVENTORY_URI: {{ $sec.encryptedMongoInventoryUri }}
    MONGO_ROOT_PASSWORD: {{ $sec.encryptedMongoRootPassword }}
    MONGO_ROOT_USERNAME: {{ $sec.encryptedMongoRootUsername }}
    MONGO_USER_URI: {{ $sec.encryptedMongoUserUri }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ $sec.name }}
      namespace: {{ $ns }}
