apiVersion: v1
kind: Secret
metadata:
  name: rxpulse-secrets
  labels:
    app.kubernetes.io/part-of: rxpulse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "RxPulse@Mongo2024"

  MONGO_USER_URI: "mongodb://mongo-user:27017/userdb"
  MONGO_CATALOG_URI: "mongodb://mongo-catalog:27017/catalogdb"
  MONGO_INVENTORY_URI: "mongodb://mongo-inventory:27017/inventorydb"

  JWT_SECRET: "rxpulse_jwt_super_secret_k8s_2024"
  JWT_EXPIRES_IN: "7d"