apiVersion: v1
kind: Secret
metadata:
  name: rxpulse-secrets
  namespace: rxpulse
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password"
  MONGO_USER_URI: "mongodb://admin:password@mongo:27017/userdb?authSource=admin"
  MONGO_CATALOG_URI: "mongodb://admin:password@mongo:27017/catalogdb?authSource=admin"
  MONGO_INVENTORY_URI: "mongodb://admin:password@mongo:27017/inventorydb?authSource=admin"
  JWT_SECRET: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhd3MwMyIsIm5hbWUiOiJ2aW5heSIsImFkbWluIjp0cnVlLCJpYXQiOjE1MTYyMzkwMjJ9.RtOlTaltebP2E6i8mBWID7YRZdfZPj4LswQaDsJ-ZII"
