require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('./models/Category');
const Medicine = require('./models/Medicine');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://mongo-catalog:27017/catalog_db';

const categories = [
  { name: 'Antibiotics', description: 'Medicines that kill or inhibit bacteria', isActive: true },
  { name: 'Painkillers', description: 'Medicines for pain relief', isActive: true },
  { name: 'Vitamins', description: 'Vitamin and mineral supplements', isActive: true },
  { name: 'Antidiabetics', description: 'Medicines for diabetes management', isActive: true },
  { name: 'Antihypertensives', description: 'Medicines for blood pressure control', isActive: true },
  { name: 'Antacids', description: 'Medicines for acidity and stomach issues', isActive: true },
  { name: 'Antihistamines', description: 'Medicines for allergies', isActive: true },
  { name: 'Syrups', description: 'Liquid medicines and syrups', isActive: true },
];

const medicines = [
  {
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin',
    manufacturer: 'Sun Pharma',
    category: 'Antibiotics',
    batchNumber: 'BATCH-AMX-001',
    expiryDate: new Date('2026-08-01'),
    unitPrice: 12.50,
    unit: 'capsules',
    requiresPrescription: true,
    description: 'Broad-spectrum antibiotic used to treat bacterial infections',
    isActive: true,
  },
  {
    name: 'Azithromycin 250mg',
    genericName: 'Azithromycin',
    manufacturer: 'Cipla',
    category: 'Antibiotics',
    batchNumber: 'BATCH-AZI-002',
    expiryDate: new Date('2026-10-15'),
    unitPrice: 28.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Antibiotic used for respiratory and skin infections',
    isActive: true,
  },
  {
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol',
    manufacturer: 'GSK',
    category: 'Painkillers',
    batchNumber: 'BATCH-PCM-003',
    expiryDate: new Date('2027-01-01'),
    unitPrice: 2.50,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Used for fever and mild to moderate pain relief',
    isActive: true,
  },
  {
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    manufacturer: 'Dr Reddys',
    category: 'Painkillers',
    batchNumber: 'BATCH-IBU-004',
    expiryDate: new Date('2026-06-30'),
    unitPrice: 5.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Anti-inflammatory and pain relief medicine',
    isActive: true,
  },
  {
    name: 'Diclofenac 50mg',
    genericName: 'Diclofenac Sodium',
    manufacturer: 'Novartis',
    category: 'Painkillers',
    batchNumber: 'BATCH-DCF-005',
    expiryDate: new Date('2026-09-20'),
    unitPrice: 8.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'NSAID used for pain and inflammation',
    isActive: true,
  },
  {
    name: 'Vitamin C 500mg',
    genericName: 'Ascorbic Acid',
    manufacturer: 'Himalaya',
    category: 'Vitamins',
    batchNumber: 'BATCH-VTC-006',
    expiryDate: new Date('2027-03-01'),
    unitPrice: 3.50,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Vitamin C supplement for immunity',
    isActive: true,
  },
  {
    name: 'Vitamin D3 1000IU',
    genericName: 'Cholecalciferol',
    manufacturer: 'Abbott',
    category: 'Vitamins',
    batchNumber: 'BATCH-VTD-007',
    expiryDate: new Date('2026-12-01'),
    unitPrice: 15.00,
    unit: 'capsules',
    requiresPrescription: false,
    description: 'Vitamin D supplement for bone health',
    isActive: true,
  },
  {
    name: 'Multivitamin Tablet',
    genericName: 'Multivitamin',
    manufacturer: 'Pfizer',
    category: 'Vitamins',
    batchNumber: 'BATCH-MTV-008',
    expiryDate: new Date('2027-06-01'),
    unitPrice: 8.50,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Daily multivitamin and mineral supplement',
    isActive: true,
  },
  {
    name: 'Metformin 500mg',
    genericName: 'Metformin HCL',
    manufacturer: 'Sun Pharma',
    category: 'Antidiabetics',
    batchNumber: 'BATCH-MET-009',
    expiryDate: new Date('2026-11-01'),
    unitPrice: 6.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'First-line medication for type 2 diabetes',
    isActive: true,
  },
  {
    name: 'Glipizide 5mg',
    genericName: 'Glipizide',
    manufacturer: 'Cipla',
    category: 'Antidiabetics',
    batchNumber: 'BATCH-GLP-010',
    expiryDate: new Date('2026-07-15'),
    unitPrice: 9.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Oral antidiabetic medicine for type 2 diabetes',
    isActive: true,
  },
  {
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine',
    manufacturer: 'Dr Reddys',
    category: 'Antihypertensives',
    batchNumber: 'BATCH-AML-011',
    expiryDate: new Date('2027-02-01'),
    unitPrice: 7.50,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Calcium channel blocker for hypertension',
    isActive: true,
  },
  {
    name: 'Atenolol 50mg',
    genericName: 'Atenolol',
    manufacturer: 'GSK',
    category: 'Antihypertensives',
    batchNumber: 'BATCH-ATN-012',
    expiryDate: new Date('2026-05-01'),
    unitPrice: 5.50,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Beta blocker for blood pressure and heart conditions',
    isActive: true,
  },
  {
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    manufacturer: 'Cipla',
    category: 'Antacids',
    batchNumber: 'BATCH-OMP-013',
    expiryDate: new Date('2026-08-15'),
    unitPrice: 4.50,
    unit: 'capsules',
    requiresPrescription: false,
    description: 'Proton pump inhibitor for acidity and GERD',
    isActive: true,
  },
  {
    name: 'Pantoprazole 40mg',
    genericName: 'Pantoprazole',
    manufacturer: 'Sun Pharma',
    category: 'Antacids',
    batchNumber: 'BATCH-PAN-014',
    expiryDate: new Date('2027-01-15'),
    unitPrice: 6.50,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Used for gastric ulcers and acid reflux',
    isActive: true,
  },
  {
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine HCL',
    manufacturer: 'Abbott',
    category: 'Antihistamines',
    batchNumber: 'BATCH-CTZ-015',
    expiryDate: new Date('2026-09-01'),
    unitPrice: 3.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Antihistamine for allergic rhinitis and urticaria',
    isActive: true,
  },
  {
    name: 'Loratadine 10mg',
    genericName: 'Loratadine',
    manufacturer: 'Novartis',
    category: 'Antihistamines',
    batchNumber: 'BATCH-LOR-016',
    expiryDate: new Date('2026-11-30'),
    unitPrice: 4.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Non-drowsy antihistamine for allergy relief',
    isActive: true,
  },
  {
    name: 'Cough Syrup 100ml',
    genericName: 'Dextromethorphan',
    manufacturer: 'Himalaya',
    category: 'Syrups',
    batchNumber: 'BATCH-CSY-017',
    expiryDate: new Date('2026-10-01'),
    unitPrice: 45.00,
    unit: 'ml',
    requiresPrescription: false,
    description: 'Syrup for dry cough and throat irritation',
    isActive: true,
  },
  {
    name: 'Antacid Suspension 170ml',
    genericName: 'Aluminium Hydroxide',
    manufacturer: 'Pfizer',
    category: 'Syrups',
    batchNumber: 'BATCH-ASY-018',
    expiryDate: new Date('2026-07-01'),
    unitPrice: 55.00,
    unit: 'ml',
    requiresPrescription: false,
    description: 'Liquid antacid for instant acidity relief',
    isActive: true,
  },
  {
    name: 'Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin',
    manufacturer: 'Cipla',
    category: 'Antibiotics',
    batchNumber: 'BATCH-CIP-019',
    expiryDate: new Date('2026-04-30'),
    unitPrice: 18.00,
    unit: 'tablets',
    requiresPrescription: true,
    description: 'Fluoroquinolone antibiotic for UTI and respiratory infections',
    isActive: true,
  },
  {
    name: 'Aspirin 75mg',
    genericName: 'Acetylsalicylic Acid',
    manufacturer: 'Bayer',
    category: 'Painkillers',
    batchNumber: 'BATCH-ASP-020',
    expiryDate: new Date('2027-04-01'),
    unitPrice: 2.00,
    unit: 'tablets',
    requiresPrescription: false,
    description: 'Low-dose aspirin for pain and blood thinning',
    isActive: true,
  },
];

const seed = async () => {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to catalog_db');

    await Category.deleteMany({});
    await Medicine.deleteMany({});
    console.log('Cleared existing catalog data');

    const insertedCategories = await Category.insertMany(categories);
    console.log('Inserted ' + insertedCategories.length + ' categories');

    const insertedMedicines = await Medicine.insertMany(medicines);
    console.log('Inserted ' + insertedMedicines.length + ' medicines');

    console.log('Catalog seed completed successfully');
    process.exit(0);
  } catch (err) {
    console.error('Catalog seed failed:', err.message);
    process.exit(1);
  }
};

seed();
