apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-catalog-pvc
  namespace: rxpulse-dev
  labels:
    app: mongo-catalog
    app.kubernetes.io/part-of: rxpulse
    app.kubernetes.io/managed-by: kubectl
    environment: dev
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
