apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: rxpulse-dev
  labels:
    app: frontend
    app.kubernetes.io/part-of: rxpulse
    app.kubernetes.io/managed-by: kubectl
    environment: dev
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: frontend

  minReplicas: 2
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
          
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
